### ISSUE TITLE
/game dont change game

### ISSUE THREAD

**Issue by RileyDatLord** [Fabricio20/DiscordSelfBot#14]
When I do /game it wont change the game on my profile show thing, I tried to change it again "Game: test -> 123"

**Comment by SkyCityCZ** [comment]
For me too

**Comment by Fabricio20** [comment]
Please remember that you can't see the game change, only others. (Game statuses are not sent to yourself).

**Comment by XxxETLegacyXxx** [comment]
guys, how do i run this in the cmd? i do java -jar C:\Users\File\Downloads\DiscordSelfBot\DiscordSelfBot-2.0-SNAPSHOT.jar
