### ISSUE TITLE
DiscordSelfBOT.jar

### ISSUE THREAD

**Issue by tamaskawulfsige** [Fabricio20/DiscordSelfBot#17]
How do you run the DiscordSelfBOT.jar on step 10? and btw would be helpful if there is discord server that you are running to help people with these help

**Comment by PLASMAchicken** [comment]
java -jar DiscordSelfBOT.jar

**Comment by PLASMAchicken** [comment]
in CMD

**Comment by PLASMAchicken** [comment]
https://discord.gg/gZGNGMD Join i can help you mention me when i am on!
Will make a Tutorial here when i have time

**Comment by Fabricio20** [comment]
I will make a GUI for this SelfBot in the future, don't worry. For now it's simply pop up cmd and call java at it like you would do with a mc server.
`java -jar fileName.jar`
