### ISSUE TITLE
Cant load principal class 

### ISSUE THREAD

**Issue by RissCrew** [Fabricio20/DiscordSelfBot#22]
Hi ! 

I'm getting trouble while import your discord selfbot
I've done everything for import it and when i launch it it show me
Erreur : impossible de trouver ou charger la classe principale net.notfab.discord.selfbot.Start
Translation : 
Error : cannot find or load main class net.notfab.discord.selfbot.Start.
Can someone help me ?

**Comment by Fabricio20** [comment]
This selfbot is dead, don't really update it.
